services:
  postgres:
    image: postgres:16-alpine
    container_name: rwa-postgres
    restart: always
    environment:
      POSTGRES_USER: rwa_admin
      POSTGRES_PASSWORD: rwa_secure_pass
      POSTGRES_DB: rwa_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rwa_admin -d rwa_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: rwa-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: infra/Dockerfile.api
    container_name: rwa-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CHAIN_GATEWAY_MODE=mock
      - DATABASE_URL=postgresql://rwa_admin:rwa_secure_pass@postgres:5432/rwa_platform?schema=public
      - JWT_SECRET=super_secret_jwt_signing_key_rwa_platform_2026_ekamvistar
      - JWT_EXPIRES_IN=15m
      - ENCRYPTION_MASTER_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: infra/Dockerfile.worker
    container_name: rwa-worker
    restart: always
    environment:
      - NODE_ENV=development
      - CHAIN_GATEWAY_MODE=mock
      - DATABASE_URL=postgresql://rwa_admin:rwa_secure_pass@postgres:5432/rwa_platform?schema=public
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: infra/Dockerfile.web
    container_name: rwa-web
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  pgdata:
  redisdata:
