FROM node:20-alpine
WORKDIR /app
RUN npm install -g pnpm@10.28.2

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages ./packages
COPY apps/api/package.json ./apps/api/package.json
COPY apps/web/package.json ./apps/web/package.json
COPY apps/worker/package.json ./apps/worker/package.json
COPY apps/worker ./apps/worker

RUN pnpm install --frozen-lockfile

ENV NODE_ENV=development
WORKDIR /app/apps/worker
CMD ["node", "src/worker.js"]
