---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/ekamvistar.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &EkamVistarOrg
    Name: EkamVistarMSP
    ID: EkamVistarMSP
    MSPDir: crypto-config/peerOrganizations/ekamvistar.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('EkamVistarMSP.admin', 'EkamVistarMSP.peer', 'EkamVistarMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('EkamVistarMSP.admin', 'EkamVistarMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('EkamVistarMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('EkamVistarMSP.peer')" }

  - &IssuerOrg
    Name: IssuerMSP
    ID: IssuerMSP
    MSPDir: crypto-config/peerOrganizations/issuer.ekamvistar.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('IssuerMSP.admin', 'IssuerMSP.peer', 'IssuerMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('IssuerMSP.admin', 'IssuerMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('IssuerMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('IssuerMSP.peer')" }

  - &VerifierOrg
    Name: VerifierMSP
    ID: VerifierMSP
    MSPDir: crypto-config/peerOrganizations/verifier.ekamvistar.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('VerifierMSP.admin', 'VerifierMSP.peer', 'VerifierMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('VerifierMSP.admin', 'VerifierMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('VerifierMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('VerifierMSP.peer')" }

  - &ComplianceOrg
    Name: ComplianceMSP
    ID: ComplianceMSP
    MSPDir: crypto-config/peerOrganizations/compliance.ekamvistar.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('ComplianceMSP.admin', 'ComplianceMSP.peer', 'ComplianceMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('ComplianceMSP.admin', 'ComplianceMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('ComplianceMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('ComplianceMSP.peer')" }

  - &InvestorOrg
    Name: InvestorMSP
    ID: InvestorMSP
    MSPDir: crypto-config/peerOrganizations/investor.ekamvistar.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('InvestorMSP.admin', 'InvestorMSP.peer', 'InvestorMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('InvestorMSP.admin', 'InvestorMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('InvestorMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('InvestorMSP.peer')" }

  - &AuditorOrg
    Name: AuditorMSP
    ID: AuditorMSP
    MSPDir: crypto-config/peerOrganizations/auditor.ekamvistar.com/msp
    Policies:
      Readers: { Type: Signature, Rule: "OR('AuditorMSP.admin', 'AuditorMSP.peer', 'AuditorMSP.client')" }
      Writers: { Type: Signature, Rule: "OR('AuditorMSP.admin', 'AuditorMSP.client')" }
      Admins: { Type: Signature, Rule: "OR('AuditorMSP.admin')" }
      Endorsement: { Type: Signature, Rule: "OR('AuditorMSP.peer')" }

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer1.ekamvistar.com:7050
    - orderer2.ekamvistar.com:7052
    - orderer3.ekamvistar.com:7054
  EtcdRaft:
    Consenters:
      - Host: orderer1.ekamvistar.com
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/ekamvistar.com/orderers/orderer1.ekamvistar.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/ekamvistar.com/orderers/orderer1.ekamvistar.com/tls/server.crt
      - Host: orderer2.ekamvistar.com
        Port: 7052
        ClientTLSCert: crypto-config/ordererOrganizations/ekamvistar.com/orderers/orderer2.ekamvistar.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/ekamvistar.com/orderers/orderer2.ekamvistar.com/tls/server.crt
      - Host: orderer3.ekamvistar.com
        Port: 7054
        ClientTLSCert: crypto-config/ordererOrganizations/ekamvistar.com/orderers/orderer3.ekamvistar.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/ekamvistar.com/orderers/orderer3.ekamvistar.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 100
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
    - *OrdererOrg
  Policies:
    Readers: { Type: ImplicitMeta, Rule: "ANY Readers" }
    Writers: { Type: ImplicitMeta, Rule: "ANY Writers" }
    Admins: { Type: ImplicitMeta, Rule: "MAJORITY Admins" }
    BlockValidation: { Type: ImplicitMeta, Rule: "ANY Writers" }
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers: { Type: ImplicitMeta, Rule: "ANY Readers" }
    Writers: { Type: ImplicitMeta, Rule: "ANY Writers" }
    Admins: { Type: ImplicitMeta, Rule: "MAJORITY Admins" }
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  RwaChannelProfile:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *EkamVistarOrg
        - *IssuerOrg
        - *VerifierOrg
        - *ComplianceOrg
        - *InvestorOrg
        - *AuditorOrg
